### ISSUE TITLE
USER STORY: Initial Deployment to Heroku

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/blossom-therapy#15]
As a **developer**, I want to **deploy to Heroku** so that **I can verify initial set up**.

## Acceptance Criteria
- [x]  The Django project is deployed successfully on Heroku.
- [x] The app is accessible at the Heroku domain name.
- [x] The app is configured correctly for production environment.
- [x] The app is running without any errors.
- [x] The app is connected to a database.

## Tasks
- [x] Configure the project settings.
- [x] Create a requirements.txt file.
- [x] Create `Procfile`.
- [x] Configure the Heroku environment.
- [x] Test the app.
