### ISSUE TITLE
USER STORY: Create New Insight

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/blossom-therapy#22]
As a **registered user**, I want to **create posts** so that **I can upload them on the platform**.

## Acceptance Criteria
- [x] User can compose a new blog post with text and image.
- [x] Draft is stored in my dashboard/profile area for later editing or publishing.

## Tasks
- [x] Design and implement the content creation form for composing posts.
- [x] Develop the functionality to save draft posts and store them in the user's dashboard.
