### ISSUE TITLE
USER STORY: Update Developer Profile

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/blossom-therapy#51]
As a **developer**, I want to **update my profile information* so that **I can keep my information current and accurate**.

## Acceptance Criteria
- [x] The form allows the developer to update their bio.
- [x] The form allows the developer to update their photo.
- [x] The form allows the developer to update the resume download link.
- [x] The form allows the developer to update the GitHub portfolio link.
- [x] Changes are saved and displayed correctly on the Developer Profile page.

## Tasks
- [x] Create an editable form for the developer profile.
- [x] Allow updating of the photo.
- [x] Allow updating of the bio.
- [x] Allow updating of the resume download link.
- [x] Allow updating of the GitHub portfolio link.
